### ISSUE TITLE
Docker image for glassfish to replace oracle/glassfish

### ISSUE THREAD

**Issue by nicodeur** [eclipse-ee4j/glassfish#22598]
# "Docker image for glassfish"

## Environment Details
* GlassFish Version (and build number): 5
* JDK version: 1.8
* OS: Docker Linux
* Database: /

----------

## Problem Description
Since GlassFish Docker image `oracle/glassfish` has been removed from the Oracle docker-images repository as part of the donation process to the Eclipse Foundation, I can't continue to build my docker image from oracle/glassfish:5.0-web.

Are you going to create a new official image to replace `oracle/glassfish` ? I can't find any official images for glassfish 5 today on docker hub ...

## Steps to reproduce
Dockerfile : 
```
FROM oracle/glassfish:5.0-web

```
## Impact of Issue
I can't continue to build my docker image to deliver on docker hub my new version of my open-source project

**Comment by arindam-bandyopadhyay** [comment]
GlassFish 5.0 can work with JDK 1.8.0.151<=GlassFish_Java_Version<= 1.8.0.141. The reason behind that is https://github.com/javaee/glassfish/issues/22407. Though the issue is fixed in the upstream repository(Glassfish 5.0.1), but it's not backported to GlassFish 5.0(and there is no plan of backporting either)
Oracle Linux team has removed older RPMs( JDK 1.8.0.151) as part of the repo cleanup: https://blogs.oracle.com/linux/upcoming-change-to-oracle-linux-package-channels. JDK 1.8.0.151 has known vulnerability and to publish the GlassFish docker image we should use only the latest JDK that is available on ol7_latest repo. However, as GlassFish 5.0 doesn't work with the latest JDK8. So recreating of GlassFish 5.0 docker image is not possible.
However, as https://github.com/javaee/glassfish/issues/22407 is fixed in GlassFish 5.0.1, we would create docker image for GlassFish 5.0.1 when we will be releasing GlassFish 5.0.1

**Comment by poikilotherm** [comment]
Sorry to bother (I know you guys are really busy with 5.1) and hoping this thread is ok for my question: any ETA for the release of 5.0.1?

Willing to build a Dockerfile and create a PR...

**Comment by pdurbin** [comment]
Congrats on the first release! I see that 5.1 is out!

https://github.com/javaee/glassfish/issues/22407 is a 404 so it's somewhat difficult to follow this issue.

For anyone interested in official Eclipse GlassFish Docker images, is this the right issue to track?

**Comment by edbratt** [comment]
You can follow this Eclipse GlassFish issue: 
https://github.com/eclipse-ee4j/glassfish/issues/22598 (I just searched 
for 22407, in the GitHub search)

**Comment by chabala** [comment]
I am interested in having an official public GlassFish docker image exist.

**Comment by dmatej** [comment]
> There also exists a non-official glasshfish image with a few hundred pulls. But having a canonical, official image would be preferred.

Quick question, because I always used docker images prepared, tuned and customized for the concrete use case: what is your use case? There is quite lot issues related to that:

1) Which versions of the JDK it should use? Sure, for GF7 is the JDK17 the best, and honestly, it is an Eclipse project, so automatically I would create an image which would use Temurin JDK.

2) What about updates? There are JDK updates, we plan GlassFish updates soon too.

3) Creating Dockerfile is quite trivial, sure, we can do that. But I would use such image probably just for examples, lessons, not for production.

4) One very critical, basically you noticed it: now DockerHub is not so open as it was years before, for free accounts it limits user accounts, size and I am not sure if it doesn't limit traffic too (did not look for a while).

5) Currently I believe both Artifactory and Nexus support docker repositories, so there's always some way ...

About the https://hub.docker.com/_/glassfish repo - I even don't know who was the maintainer, so we could adopt it. Years before somebody simply created it.

**Comment by chabala** [comment]
> I always used docker images prepared, tuned and customized for the concrete use case: what is your use case?

I'm not sure that having a use case is relevant. I would agree that having a tuned docker image is better for production use. But the absence of an official image is a perception problem; so is letting the official image languish with warnings of deprecation and links to images that don't exist. It's the same sort of smell as a project not having a release in a while, or a library that fails to publish to Maven Central.

Having a 'blessed' official image is its own reward, it adds credibility that the image is not malicious. Right now the only thing that comes close is IBM's ppc image: https://hub.docker.com/search?q=glassfish&source=community&image_filter=store

My use case for using any official JDK image is of the same sort: it may not be ideal for production, but I have assurance that it's not malicious, lots of other people are using it, and it was likely build by someone that knew what they were doing.

As far as what JDK should it be based on and other tuning issues, the same guidelines as other official images would apply. Build on top of other official DockerHub images, pick sensible defaults for the main image and provide tags for alternative builds, e.g. different JDK versions and providers.

> I even don't know who was the maintainer, so we could adopt it.

* AWS created it: https://github.com/docker-library/official-images/pull/288
* [brunoborges](https://github.com/brunoborges) (while at Oracle) advocated for `glassfish/server` https://github.com/docker-library/official-images/pull/1334#issuecomment-243834123
* as a result `glassfish` is deprecated https://github.com/docker-library/docs/pull/679
* `glassfish/server` is now gone for reasons unknown

Nominating a new image to become the DockerHub official `glassfish` image should be relatively painless.

**Comment by arjantijms** [comment]
I'm convinced too. Let's set this too a high priority.

**Comment by chabala** [comment]
Might want to keep this open until there's a new image on DockerHub.

**Comment by dmatej** [comment]
> Might want to keep this open until there's a new image on DockerHub.

You're right!

**Comment by arjantijms** [comment]
Almost a year ago that https://github.com/docker-library/official-images/pull/14107 was created. Are we going to celebrate its anniversary?

**Comment by dmatej** [comment]
> Almost a year ago that [docker-library/official-images#14107](https://github.com/docker-library/official-images/pull/14107) was created. Are we going to celebrate its anniversary?

We will do in March, I hope ;-)

**Comment by dmatej** [comment]
Ok, after all I believe we can close this - DockerHub still fails to review and merge my [PR](https://github.com/eclipse-ee4j/glassfish.docker/pkgs/container/glassfish), but after OmniFish [donated](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3138) its [work](https://github.com/eclipse-ee4j/glassfish.docker) to the Eclipse Foundation I was able to deploy [Eclipse GlassFish 7.0.16 multiplatform image](https://github.com/eclipse-ee4j/glassfish.docker/pkgs/container/glassfish).

We also added some [documentation](https://github.com/eclipse-ee4j/glassfish.docker/wiki) how to use it.
