### ISSUE TITLE
context-root in glassfish-web.xml is ignored

### ISSUE THREAD

**Issue by helper14** [eclipse-ee4j/glassfish#23525]
A 'path-to-application' set by a context-root-element in glassfish-web.xml is not regarded.

## Environment Details
* GlassFish Version: 6.1
* JDK version: jdk-11.0.11+9
* OS: Win10
* Database:

----------

my glassfish-web.xml:
`
<glassfish-web-app error-url="">
    <context-root>/somepath</context-root>
     ...
`
The application can be called under: http://localhost:8080/war-packge-name/ instead of http://localhost:8080/somepath/

## Steps to reproduce
create a new maven web-jar
adjust the context-root in glassfish-web.xml
deploy by cargo on Glassfish 6.1
...

**Comment by helper14** [comment]
Still an open issue ...

**Comment by jaceabreu** [comment]
I haven't observed this issue with our manual deployments.  I have been using GlassFish since version 5.1, first with projects using Ant as a build tool, then with Gradle.  We don't use the cargo deployment tool.  I believe all of my web projects have both a web.xml and a glassfish-web.xml configuration file.  Both of those configuration files must be in the WEB-INF folder of your built web project.
Also, it appears as if the cargo Maven plugin has the ability to provide the context path of the application, as well.  See:
```
<deployable>
    <groupId>${project.groupId}</groupId>
    <artifactId>${project.artifactId}</artifactId>
    <type>war</type>
    <properties>
        <context>/mywebapp</context>
    </properties>
</deployable>
```
For GlassFishto use the context path from the glassfish-web.xml the context path provided on the deploy command must be left blank.  Be sure you're not setting the context path in your plugin configuration and check any debug lines to be sure it's not being defaulted by the cargo plugin to some other value.  This seems like it might be an issue with your deployment plugin rather than GlassFish, though.

**Comment by helper14** [comment]
@jaceabreu 
Thank you for your reply! I deployed the war by asadmin without cargo and the context-root was considered properly. So you are right: It is a cargo problem.
