### ISSUE TITLE
Any version of MariaDB jdbc driver higher than 2.7.1 does not works

### ISSUE THREAD

**Issue by szarza** [eclipse-ee4j/glassfish#23777]
Can't use a MariaDB jdbc driver ([JConnector](https://mariadb.com/kb/en/mariadb-connector-j/)) higher than 2.7.1 because Glassfish is showing the following error: `Reason : com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: url not set`

## Environment Details
* Tested on GlassFish >= 5.1 (including 6.2.4)
* JDK version: JDK 17
* OS: RHEL 8
* Database: MariaDB

----------

## Steps to reproduce

1. Put the mariadb jdbc driver file `mariadb-java-client-3.0.3.jar` in glassfish\domains\[domain]\lib

2. Create the following DataSource using commands or web admin:

```
create-jdbc-connection-pool --datasourceclassname=org.mariadb.jdbc.MariaDbDataSource --restype=javax.sql.DataSource --maxpoolsize=64 --statementtimeout=10 --isconnectvalidatereq=true --validationmethod=table --validationtable=nodo --property=databaseName=calypso:serverName=localhost:portNumber=3306:password=xxxxx:user=calypso CalypsoPool

create-jdbc-resource --connectionpoolid CalypsoPool jdbc/CalypsoServerDS
```
3. Glassfish is showing the following error:

```
[2022-02-03T09:16:22.393+0100] [glassfish 6.2] [WARNING] [poolmgr.create_resource_error] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.resource.allocator] [tid: _ThreadID=128 _ThreadName=admin-listener(5)] [timeMillis: 1643876182393] [levelValue: 900] [[
  RAR5038:Unexpected exception while creating resource for pool CalypsoPool. Exception : jakarta.resource.spi.ResourceAllocationException: Connection could not be allocated because: url not set]]

[2022-02-03T09:16:22.394+0100] [glassfish 6.2] [WARNING] [poolmgr.get_connection_failure] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors] [tid: _ThreadID=128 _ThreadName=admin-listener(5)] [timeMillis: 1643876182394] [levelValue: 900] [[
  RAR5117 : Failed to obtain/create connection from connection pool [ CalypsoPool ]. Reason : com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: url not set]]

[2022-02-03T09:16:22.395+0100] [glassfish 6.2] [WARNING] [jdbc.exc_get_conn] [javax.enterprise.resource.resourceadapter.com.sun.gjc.spi] [tid: _ThreadID=128 _ThreadName=admin-listener(5)] [timeMillis: 1643876182395] [levelValue: 900] [[
  RAR5114 : Error allocating connection : [Error in allocating a connection. Cause: Connection could not be allocated because: url not set]]]

``` 

Works with `mariadb-java-client-2.7.1.jar`, but with higher versions.

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
[//]: # "Please choose one each Type, Component, and Priority label"

You can't use updated versions of MariaDB drivers

**Comment by arjantijms** [comment]
Thanks for the report. A quick investigation shows the issue is that essentially MariaDB did a simplification in their data source and removed most of the properties you are setting:

https://github.com/mariadb-corporation/mariadb-connector-j/commit/e5e95ddfd6ceed7bce757a5b2521c61208e59700#diff-e45cd5e2e403f140740e4c43c12006e73d4a4db910dfa1fea0f6cc2a0a396735

To see the entire file, the were still here:

https://github.com/mariadb-corporation/mariadb-connector-j/blob/b4598531228e67f66c1cedad9aa79e2a354c6d0b/src/main/java/org/mariadb/jdbc/MariaDbDataSource.java

But all removed here:

https://github.com/mariadb-corporation/mariadb-connector-j/blob/e5e95ddfd6ceed7bce757a5b2521c61208e59700/src/main/java/org/mariadb/jdbc/MariaDbDataSource.java

A few properties were added back later:

https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/src/main/java/org/mariadb/jdbc/MariaDbDataSource.java

It's been a while that I've worked with the connection pool implementations, so I've to check again how exactly this is generally handled. For starters you could look for examples of how the MariaDbDataSource is actually supposed to be used right now with other servers and pools, as you will seeming have the same problem there if using these properties.

My guess would be the easiest solution would be to update GF to handle the `setUrl` method, which it doesn't do directly right now:

https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceObjectBuilder.java#L88

**Comment by arjantijms** [comment]
Url is of course supported via the drivers properties there. So no changes are needed and something like the following should work:

```
create-jdbc-connection-pool --datasourceclassname=org.mariadb.jdbc.MariaDbDataSource --restype=javax.sql.DataSource --maxpoolsize=64 --statementtimeout=10 --isconnectvalidatereq=true --validationmethod=table --validationtable=nodo --property=url="jdbc\\:mariadb\\://localhost\\:3306/calypso":password=xxxxx:user=calypso CalypsoPool
```

**Comment by szarza** [comment]
Thanks for the suggestion but, unfortunately, it doesn't work like that.

It only works if I add "user" to the url property. But it seems that this property is also needed in duplicate, as a separate property, because if I remove it, it doesn't work either.

`create-jdbc-connection-pool --datasourceclassname=org.mariadb.jdbc.MariaDbDataSource --restype=javax.sql.DataSource --maxpoolsize=64 --statementtimeout=10 --isconnectvalidatereq=true --validationmethod=table --validationtable=nodo --property=url="jdbc\\:mariadb\\://localhost\\:3306/calypso?user\\=calypso":password=xxxx:user=calypso CalypsoPool
`
