### ISSUE TITLE
Make stop-domain more robust

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#24187]
In years we all experiences some issues with stop-domain command. They are not well reproducible, often depend on used OS or filesystem, speed of the CPU ... with weird consequences. The worst is that sometimes the command says the domain stopped, but it did not (yet).

Some examples I catched recently will follow here.

### PID.PREV could not be found

* Is this ok or not? Is the domain running?
* Catched in Eclipse's TCK run with GF7M9.
```
+ /root/vi/glassfish7/glassfish/bin/asadmin stop-domain --kill
Picked up JAVA_TOOL_OPTIONS: -Xmx6G
Can not find the process ID of the server.  It is supposed to be here: /root/vi/glassfish7/glassfish/domains/domain1/config/pid.prev.  Unable to kill the process.
Command stop-domain failed.
```

### Could not stop, inaccessible admin cache
* Timeout, why?
* What is admin cache and why it cannot be read?
* Catched in Eclipse's TCK run with GF7M9.
```
+ /root/ri/glassfish7/glassfish/bin/asadmin --user admin --passwordfile /root/admin-password.txt stop-domain
Picked up JAVA_TOOL_OPTIONS: -Xmx6G
Cannot read admin cache file for cache/localhost_4848/__locations
Cannot read admin cache file for cache/localhost_4848/stop-domain
Waiting for the domain to stop ...........................................................
Timed out (60 seconds) waiting for the domain to stop.
Command stop-domain failed.
```

### Domain stopped, but another start fails, port still used.

* Seen on private Jenkins
* Read the code and check the shutdown correctly releases all ports.

**Comment by OndroMih** [comment]
I tried to find out what the admin cache is and it looks like it's a cache for metadata about admin commands retrieved from a remote GF server so that the Admin CLI doesn't have to fetch it each time: [RemoteAdminCommand.java#L1129](https://github.com/eclipse-ee4j/glassfish/blob/9a68cc8076d14c77aba791fd5c955b7c7a175593/nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteAdminCommand.java#L1129). It's not a problem if the file doesn't exist, the info will be retrieved from the remote server and then cached locally. But it's strange that the WARNING is logged, because it means that the data is cached but either the file cannot be read or the data is corrupted: [AdminCacheFileStore.java#L66](https://github.com/eclipse-ee4j/glassfish/blob/18953db0fd7b28648314df13d7b349dc44d33f2a/nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/cache/AdminCacheFileStore.java#L66). Maybe the cached data is from an older version of GlassFish or something. But even then it's not an issue, because the metadata will simply be fetched from the remove server.

**Comment by OndroMih** [comment]
> PID.PREV could not be found

I think this could happen if there's a different GF running that doesn't match the directory of the domain we want to stop. In that case, the `kill` switch will not find the PID file in the domain directory, because the server for that domain isn't running.

To cover this case, we should improve the `kill` switch so that it finds out the PID of the server running on the admin port and kills the process with that PID.

**Comment by dmatej** [comment]
I'm already working on that, data are from the same version, or better said data are NOT, they don't exist, because GF tries to use user's home which is / on Eclipse's TCK Jenkins and is not writable.
There are yet other issues, but all together results in a state that domain can be started but cannot be stopped in any way except manual usage of the kill -9.
