### ISSUE TITLE
securityContext.isCallerInRole() incorrectly returning false after authenticating until next page reload

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#24196]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish 7 M10
* JDK version: OpenJDK Runtime Environment Zulu17.36+13-CA (build 17.0.4+8-LTS)
* OS:Ubuntu 22.04.1 LTS
* Database: N/A

----------

## Problem Description
The same issue that was reported for Payara: https://github.com/payara/Payara/issues/4734

> Checking with `securityContext.isCallerInRole("admin")` incorrectly returns false whereas `request.isUserInRole("admin")` returns true. Refreshing the page results in `securityContext.isCallerInRole("admin")` then correctly returning true. Note, the EJB container is affected by this bug, if a Singleton bean requires the admin role, after logging in the principal (which was created) is "missing" the role until you refresh the page.

## Steps to reproduce

The same as in https://github.com/payara/Payara/issues/4734 with this reproducer app (modified for Jakarta EE 10): 
[security-bug.zip](https://github.com/eclipse-ee4j/glassfish/files/10095860/security-bug.zip)

## Impact of Issue
Type: Bug
Component: Security
Priority: high

**Comment by ctabin** [comment]
Maybe also related to #23757 ?

**Comment by OndroMih** [comment]
It might be related, but this issue (#24196) happens also in Payara while the one you reference #23757 you wrote doesn't happen on Payara.

**Comment by arjantijms** [comment]
This was recently fixed in 7.0.5 it seems: https://github.com/eclipse-ee4j/glassfish/commit/eb194a55203153729f24a33067f9666cf2857a55

I discovered the mistake there for a slightly different bug, but it has fixed this one too.

The reproducer now shows both ways to detect the right role:

<img width="418" alt="security-debug" src="https://github.com/eclipse-ee4j/glassfish/assets/3037006/ce6d68ea-3c83-47dc-a4be-d473c2b5d8ca">
