### ISSUE TITLE
glassfish.org is missing parts of the documentation / 404 Not Found

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/glassfish#24431]
Apparently some parts of the documentation are missing on glassfish.org.

In particular, the following link exists on the web site, but leads to 404 Not Found:

https://glassfish.org/docs/latest/reference-manual/create-virtual-server.html#create-virtual-server

**Comment by dmatej** [comment]
These links changed with the new UI of the documentation. What was the source page of the URL? That should be updated.
https://glassfish.org/docs/latest/reference-manual.html#create-virtual-server

**Comment by OndroMih** [comment]
I found some links like that in https://glassfish.org/docs/latest/administration-guide.html.
They go to href like: reference-manual/list-virtual-servers.html#list-virtual-servers) but they should go to reference-manual.html#list-virtual-servers). Those should have been fixed with: https://github.com/eclipse-ee4j/glassfish/commit/4ad70595b458b708017acab74918dee1c759f695, I need to check what's happening.

**Comment by OndroMih** [comment]
I found out. The links are fixed in the snapshot documentation: https://glassfish.org/docs/SNAPSHOT/administration-guide.html. We need to backport it to the 7.0.0 documentation, which is now linked from the "latest" alias. Or move the "latest" to newer docs.

**Comment by OndroMih** [comment]
The links should get fixed with this PR: https://github.com/eclipse-ee4j/glassfish/pull/24447

**Comment by mkarg** [comment]
@OndroMih Thanks a lot! You are awesome! :-)

**Comment by OndroMih** [comment]
This is now fixed at https://glassfish.org/docs/latest/. I think we can close this issue now.
