### ISSUE TITLE
Share the download link to the GenericJMSRA resource archive (genericra.rar)

### ISSUE THREAD

**Issue by ahfarag** [eclipse-ee4j/glassfish#24699]
## Environment Details
* GlassFish Version (and build number): Eclipse GlassFish 7.0.10, Jakarta EE Platform, 10
* JDK version: openjdk version "21.0.1" 2023-10-17
* OS: Ubuntu
* Database: NA

----------

## Problem Description
I am trying to follow the documentation to use IBM MQ with Glassfish. I followed the steps in the documentation [Deploy the GenericJMSRA Resource Archive](https://glassfish.org/docs/latest/administration-guide.html#deploy-the-genericjmsra-resource-archive) but I am not able to find the deployment file.

## Steps to reproduce
1. Follow the steps in the documentation [Deploy the GenericJMSRA Resource Archive](https://glassfish.org/docs/latest/administration-guide.html#deploy-the-genericjmsra-resource-archive) 
1. The first step is "Download the GenericJMSRA resource archive (genericra.rar).". However, it is not clear where to download the rar file.

## Impact of Issue
Unable to [integrate Oracle WebLogic JMS and IBM WebSphere MQ JMS providers through the use of the Generic Resource Adapter for JMS (GenericJMSRA)](https://glassfish.org/docs/latest/administration-guide.html#using-the-generic-resource-adapter-for-jms-to-integrate-supported-external-jms-providers).

**Comment by pzygielo** [comment]
I think `genericra.rar` has not been published to central since javaee donation to EF.

1. [genericmessagingra](https://github.com/eclipse-ee4j/genericmessagingra)
1. check [GitHub workflow](https://github.com/eclipse-ee4j/genericmessagingra/blob/master/.github/workflows/ant.yml) for environment variables https://github.com/eclipse-ee4j/glassfish/blob/4ffa5c089097ecc74abeae679f61a3106442f45a/.github/workflows/ant.yml#L9-L11 that need to be set (two) and adjust values for your needs
1. use ancient JDK (in GH action temurin 8 is used) and Apache Ant to build `genericra.rar` locally - it will land in `build/dist` directory
1. propose changes/open PRs for documentation that you'd like to see

**Comment by ahfarag** [comment]
Thanks, @pzygielo  for your reply. I have successfully been able to build the project. Since the build has not been published to the central repo, I created a docker build file to make it easier for anyone who wants quicker access to the build without going into the details of the environment requirements. I created [a pull request for it here](https://github.com/eclipse-ee4j/genericmessagingra/pull/89).
