### ISSUE TITLE
WebsocketFilterWrapper casts the wrapped request as a RequestFace, causes classCastException

### ISSUE THREAD

**Issue by mduchemin** [eclipse-ee4j/glassfish#24712]
## Environment Details
* GlassFish Version: Eclipse GlassFish 7.0.11 (commit: ad98c44e896c7a78cb4eb2a84ca9fac450fb3a10)
* JDK version: OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
* OS: Windows
* Database: none

----------

## Problem Description
My application uses a programmatically declared Filter to add overrides to a Websocket request before it is processed.
The filter preforms some operation, then creates a wrappedRequest:

MyApplicationFilter.java
```
        public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
...
		ServletRequest wrappedRequest = new HttpServletRequestWrapper((HttpServletRequest) request) {
                     ... //overrides in here, omitted due to not being relevant
		};
		chain.doFilter(wrappedRequest, response);
        }
...
```

When reaching org.apache.catalina.core.WebSocketFilterWrapper.java further down the Filter chain:
https://github.com/eclipse-ee4j/glassfish/blob/e1f0c9409bdf0c538733de35d6a5336457a3862c/appserver/web/web-core/src/main/java/org/apache/catalina/core/WebSocketFilterWrapper.java#L72

Filter attempts to cast the wrappedRequest as a FaceRequest, causes ClassCastException then fails silently (no error in logs)

## Steps to reproduce
Currently no easy-to-run code sample, but if required I can build something.
Let me know in comment if this is required.

## Impact of Issue
Causes websocket channel initialization to fail silently. No error log, no error message on client-side (just that connection had failed, without an error code or error message)

In order to make the wrappedRequest created in my application filter compatible with WebsocketFilterWrapper, I would need to use FacadeRequest instead of HttpServletRequestWrapper in application code, which I think is unexpected, as RequestFacade is specific to the server implementation, instead of the generic API HttpServletRequestWrapper which should be supported regardless of which environement the application is executed into.

**Comment by OndroMih** [comment]
I think it's enough to change the line 72 with `(RequestFacade) super.getRequest()` to:

HttpServletRequest wrappedRequest = (HttpServletRequest) super.getRequest();

@mduchemin, are you able to change this in GlassFish, build it and test that it works for you?

**Comment by mduchemin** [comment]
will clone and build to try it, but I assume it should work.

However, there isn't a getContextPath(boolean maskDefaultContextMapping) in the  HttpServletRequest API. (only the no-arguments getContextPath())

[https://jakarta.ee/specifications/servlet/4.0/apidocs/javax/servlet/http/httpservletrequest#getContextPath--](https://jakarta.ee/specifications/servlet/4.0/apidocs/javax/servlet/http/httpservletrequest#getContextPath--)

So you would need to change line 73 as well:
https://github.com/eclipse-ee4j/glassfish/blob/e1f0c9409bdf0c538733de35d6a5336457a3862c/appserver/web/web-core/src/main/java/org/apache/catalina/core/WebSocketFilterWrapper.java#L73

RequestFacade has a no-argument getContextPath:
https://github.com/eclipse-ee4j/glassfish/blob/d322a5705f498a16210ceee9e6b7762a9cfa739c/appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java#L489C19-L489C33

but I'm not familiar enough with the design of Glassfish to tell whether or not the maskDefaultContextMapping is important in this case.

**Comment by OndroMih** [comment]
You are right, I made a quick judgement. It looks like the filter in GlassFish needs to access the internal request object.

the best solution would be to change the order of the filters so that the internal GlassFish filter is executed first. However, I don’t how to do it yet. The servletContext API doesn’t to specify the order so it would have to be done by some other way, using internal GlassFish APIs.

**Comment by mduchemin** [comment]
FYI, built glassfish locally with the proposed changes to WebSocketFilterWrapper and tested against my existing app.

With the 2 changes, I can run my app as before (same as earlier Glassfish version).

As mentioned, i replaced the getContextPath call with the no argument one, which works in my case, but I don't know enough about GF's to say whether this would introduce side effects in other use cases.

**Comment by szarza** [comment]
Hi @OndroMih:
I've tried version 7.0.12 and this issue is still present causing websocket channel initialization to fail silently. I thought it was solved by #24756, but is not... is it?

**Comment by OndroMih** [comment]
Hi @szarza, no, it wasn't addressed by https://github.com/eclipse-ee4j/glassfish/issues/24756. That fix only changes the order of servlet context initializers, not filters. And it's only related to Faces and WebSocket initilaizer. For this issue, we would have to change the order of servlet filters.

Now that I think about it, it might be dangerous to solve this by executing the GlassFish WebSocker filter before custom filters, because the WebSocket filter modifies the response and it might break some existing filters that expect to be executed before the GlassFish WebSocket filter.

So, a better solution is to change `WebSocketFilterWrapper` to work with any `ServletRequest` rather than to cast to `RequestFacade`, if possible.

**Comment by OndroMih** [comment]
Hi @mduchemin, 

> As mentioned, i replaced the getContextPath call with the no argument one, which works in my case, but I don't know enough about GF's to say whether this would introduce side effects in other use cases.

This solution works for usual applications but breaks applications configured as the default web module. When those applications receive a request with a context root, the context root is masked by default (the application thinks that it's deployed to the root context). In the filter, the masking should be disabled so that the request to the websocket channel contains the context root, because the websocket channel is only created on the app context and not on the root context.

Can you try what I suggested in my previous comment:

> WebSocketFilterWrapper should try to find an instance of RequestFacade by calling getRequest() repetitively, until it's either instance of RequestFacade (and then cast it) or until it's null, and then just call wrappedRequest.getContextPath()

I believe it should work for you in the same way as your solution and it should also keep the correct behavior for default web modules. Can you then raise a pull request with the code changes?

**Comment by peacekiller** [comment]
I'm using Glassfish 7.0.x with Spring-Security 6.1 and I have the same ClassCastException when I send a request to my websocket endpoint.

This is my workaround. However, I'm still not sure what I'm accidentally undermining...
I implmented a servlet-filter mapped to the endpoints path:

```
@Override
public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain chain) throws I OException, ServletException {
    chain.doFilter(unwrapRequest(servletRequest), servletResponse);
}

ServletRequest unwrapRequest(ServletRequest request) {
    ServletRequest unwrapped = request;
    int count = 0;
    while (unwrapped instanceof ServletRequestWrapper wrapper) {
        if (count >= MAX_UNWRAP_LOOPS) {
            break;
        }
        unwrapped = wrapper.getRequest();
        count++;
    }
    return unwrapped;
}


```

**Comment by OndroMih** [comment]
@peacekiller , it looks like your workaround is the same thing that I suggested earlier but implemented in the application as a filter. It's better to implement the same solution in GlassFish, so that it doesn't have any side-effects. The `unwrapRequest` request method should be used in the `WebSocketFilterWrapper` in GlassFish to find the underlying `RequestFacade` instead of just casting the request to `RequestFacade`.

**Comment by OndroMih** [comment]
I raised a pull request with the fix I described earlier: https://github.com/eclipse-ee4j/glassfish/pull/25107

**Comment by OndroMih** [comment]
@mduchemin , @szarza , @peacekiller , I prepared a fix in https://github.com/eclipse-ee4j/glassfish/pull/25107, if you want to try it.
